FROM eclipse-temurin:25-jre
WORKDIR /app
COPY zygererp/build/libs/zygererp-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 9090
ENTRYPOINT ["sh", "-c", "java -jar app.jar --spring.datasource.url=${DB_URL:-jdbc:postgresql://localhost:5432/zyger_erp}"]
